= RabbitMQ JMS Client
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]
:source-highlighter: prettify

== Introduction

RabbitMQ is not a JMS provider but includes https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_jms_topic_exchange[a plugin]
needed to support the JMS Queue and Topic messaging models. JMS Client
for RabbitMQ implements the JMS specification on top of the
link:https://rabbitmq.com/api-guide.html[RabbitMQ Java client], thus allowing new and
existing JMS applications to connect to RabbitMQ.

RabbitMQ JMS Client supports JMS 2.0 as of 2.7.0.
It requires Java 8 or more.

The plugin and the JMS client are meant to work and be used together.

See the link:https://rabbitmq.com/java-versions.html[RabbitMQ Java libraries support page] for the support timeline
of the RabbitMQ JMS Client library.


== Components

To fully leverage JMS with RabbitMQ, you need the following components:

* the https://github.com/rabbitmq/rabbitmq-jms-client[JMS client library] and its dependent libraries.
* https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_jms_topic_exchange[RabbitMQ JMS topic selector plugin] that is included
with RabbitMQ starting with version 3.6.3. To support message selectors for JMS
topics, the RabbitMQ Topic Selector plugin must be installed on the
RabbitMQ server. Message selectors allow a JMS application to filter
messages using an expression based on SQL syntax. Message selectors
for Queues are not currently supported.

== JMS and AMQP 0-9-1

JMS is the standard messaging API for the JEE platform. It is
available in commercial and open source implementations.  Each
implementation includes a JMS provider, a JMS client library, and
additional, implementation-specific components for administering the
messaging system. The JMS provider can be a standalone implementation
of the messaging service, or a bridge to a non-JMS messaging system.

The JMS client API is standardized, so JMS applications are portable
between vendors`' implementations. However, the underlying messaging
implementation is unspecified, so there is no interoperability between
JMS implementations. Java applications that want to share messaging
must all use the same JMS implementation unless bridging technology
exists. Furthermore, non-Java applications cannot access JMS without a
vendor-specific JMS client library to enable interoperability.

AMQP 0-9-1 is a messaging protocol, rather than an API like JMS. Any
client that implements the protocol can access a broker that supports
AMQP 0-9-1. Protocol-level interoperability allows AMQP 0-9-1 clients
written in any programming language and running on any operating
system to participate in the messaging system with no need to bridge
incompatible vendor implementations.

Because JMS Client for RabbitMQ is implemented using the RabbitMQ Java
client, it is compliant with both the JMS API and the AMQP 0-9-1 protocol.

You can download the JMS 2.0 specification and API documentation from
the https://download.oracle.com/otndocs/jcp/jms-2_0_rev_a-mrel-eval-spec/index.html[Oracle Technology Network Web site].

== Limitations

Some JMS 1.1 and 2.0 features are unsupported in the RabbitMQ JMS Client:

* The JMS Client does not support server sessions.
* XA transaction support interfaces are not implemented.
* Topic selectors are supported with the RabbitMQ JMS topic selector
 plugin. Queue selectors are not yet implemented.
* SSL and socket options for RabbitMQ connections are supported, but
 only using the (default) SSL connection protocols that the RabbitMQ client provides.
* The JMS `NoLocal` subscription feature, which prevents delivery of
 messages published from a subscriber's own connection, is not supported
 with RabbitMQ. You can call a method that includes the `NoLocal`
 argument, but it is ignored.

See link:https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/jms-client-compliance.md[the JMS API compliance documentation] for a
detailed list of supported JMS APIs.

include::installation.adoc[]
include::interoperability.adoc[]
include::logging.adoc[]
include::publisher-confirm.adoc[]
include::rpc.adoc[]
include::implementation-details.adoc[]

== Further Reading

To gain better understanding of AMQP 0-9-1 concepts and interoperability of
the RabbitMQ JMS client with AMQP 0-9-1 clients, you may wish to read an
link:https://rabbitmq.com/tutorials/amqp-concepts.html[Introduction to RabbitMQ Concepts]
and browse our
link:https://rabbitmq.com/amqp-0-9-1-quickref.html[AMQP 0-9-1 Quick Reference Guide].
