== Publisher Confirms

NOTE: Publisher Confirms support is deprecated in favor of https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#sending-messages-asynchronously-jms_spec-43[asynchronous sending] (JMS 2.0).

link:https://rabbitmq.com/confirms.html#publisher-confirms[Publisher confirms] are a RabbitMQ extension to implement reliable
publishing. This feature builds on top of the AMQP protocol, but the JMS client
provides an API to use it. This allows to benefit from a reliability feature without
diverging too much from the JMS API.

Publisher confirms are deactivated by default. They can be activated by setting
a `ConfirmListener` on the `RMQConnectionFactory`:

[source,java,indent=0]
----
RMQConnectionFactory connectionFactory = new RMQConnectionFactory();
connectionFactory.setConfirmListener(context -> {
    context.getMessage(); // the message that is confirmed/nack-ed
    context.isAck(); // whether the message is confirmed or nack-ed
});
----

Note the `ConfirmListener` is not a good place to execute long-running
tasks. Those should be executed in a dedicated thread, using e.g. an `ExecutorService`.

Typical operations in a `ConfirmListener` are logging or message re-publishing (in case
of nacks). The link:https://rabbitmq.com/tutorials/tutorial-seven-java.html[publish confirms tutorial] provides more guidance. It aims for the
AMQP Java client, but principles remain the same for the JMS client.
