
== Support for Request/Reply (a.k.a. RPC)

It is possible to use JMS for synchronous request/reply use cases.
This pattern is commonly known as _Remote Procedure Call_ or _RPC_.

=== With JMS API

An RPC client can be implemented in pure JMS like the following:

[source,java,indent=0]
----
Message request = ... // create the request message
// set up reply-to queue and start listening on it
Destination replyQueue = session.createTemporaryQueue();
message.setJMSReplyTo(replyQueue);
MessageConsumer responseConsumer = session.createConsumer(replyQueue);
BlockingQueue<Message> queue = new ArrayBlockingQueue<>(1);
responseConsumer.setMessageListener(msg -> queue.add(msg));
// send request message
MessageProducer producer = session.createProducer("request.queue");
producer.send(request);
// wait response for 5 seconds
Message response = queue.poll(5, TimeUnit.SECONDS);
// close the response consumer
responseConsumer.close();
----

It's also possible to create a single reply-to destination instead of
a temporary destination for each request. This is more efficient but requires
to properly correlate the response with the request, by using e.g.
a correlation ID header. RabbitMQ's link:https://rabbitmq.com/direct-reply-to.html[direct reply-to]
is another alternative (see below).

Note this sample uses a `MessageListener` and a `BlockingQueue` to wait
for the response. This implies a network roundtrip to register an AMQP
consumer and another one to close the consumer.
`MessageConsumer#receive` could have been used as well, in this case the JMS
client internally polls the reply destination to get the response, which can result in several
network roundtrips if the response takes some time to come. The request
call will also incur a constant penalty equals to the polling interval (100 milliseconds
by default).

The server part looks like the following:

[source,java,indent=0]
----
// this is necessary when using temporary reply-to destinations
connectionFactory.setDeclareReplyToDestination(false);
...
MessageProducer replyProducer = session.createProducer(null);
MessageConsumer consumer = session.createConsumer("request.queue");
consumer.setMessageListener(message -> {
    try {
        Destination replyQueue = message.getJMSReplyTo();
        if (replyQueue != null) {
            // create response and send it
            Message response = ...
            replyProducer.send(replyQueue, response);
        }
    } catch (JMSException e) {
        // deal with exception
    }
});
----

Note the `connectionFactory.setDeclareReplyToDestination(false)`
statement: it is necessary when using temporary reply-to destinations.
If this flag is not set to `false` on the RPC server side, the JMS
client will try to re-create the temporary reply-to destination, which will
interfere with the client-side declaration.

See https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/src/test/java/com/rabbitmq/integration/tests/RpcIT.java[this test]
for a full RPC example.

The JMS client also supports link:https://rabbitmq.com/direct-reply-to.html[direct reply-to], which is faster as it doesn't imply
creating a temporary reply destination:

[source,java,indent=0]
----
Message request = ...
// use direct reply-to
RMQDestination replyQueue = new RMQDestination(
    "amq.rabbitmq.reply-to", "", "amq.rabbitmq.reply-to", "amq.rabbitmq.reply-to"
);
replyQueue.setDeclared(true); // don't need to create this destination
message.setJMSReplyTo(replyQueue);
MessageConsumer responseConsumer = session.createConsumer(replyQueue);
BlockingQueue<Message> queue = new ArrayBlockingQueue<>(1);
responseConsumer.setMessageListener(msg -> queue.add(msg));
// send request message
MessageProducer producer = session.createProducer("request.queue");
producer.send(request);
// wait response for 5 seconds
Message response = queue.poll(5, TimeUnit.SECONDS);
// close the response consumer
responseConsumer.close();
----

Using direct reply-to for JMS-based RPC has the following implications:

* it uses automatically auto-acknowledgment
* the response must be a `BytesMessage` or a `TextMessage` as direct reply-to
 is considered an <<interoperability.adoc#destination-interoperability,AMQP destination>>. Use `response.setStringProperty("JMSType", "TextMessage")`
 on the response message in the RPC server if you want to receive a `TextMessage`
 on the client side.

See https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/src/test/java/com/rabbitmq/integration/tests/RpcWithAmqpDirectReplyIT.java[this test] for a full RPC example using direct reply-to.

=== With Spring JMS

https://docs.spring.io/spring-framework/docs/{spring-version}/reference/html/integration.html#jms[Spring JMS]
is a popular way to work with JMS as it avoids most of JMS boilerplate.

The following sample shows how a client can perform RPC with the
`JmsTemplate`:

[source,java,indent=0]
----
// NB: do not create a new JmsTemplate for each request
JmsTemplate tpl = new JmsTemplate(connectionFactory);
tpl.setReceiveTimeout(5000);
Message response = tpl.sendAndReceive(
    "request.queue",
    session -> ... // create request message in MessageCreator
);
----

This is no different from any other JMS client.

The `JmsTemplate` uses a temporary reply-to destination,
so the call to `connectionFactory.setDeclareReplyToDestination(false)`
on the RPC server side is necessary, just like with regular JMS.

RPC with direct reply-to
must be implemented with a `SessionCallback`, as the reply destination
must be explicitly declared:

[source,java,indent=0]
----
// NB: do not create a new JmsTemplate for each request
JmsTemplate tpl = new JmsTemplate(connectionFactory);
Message response = tpl.execute(session -> {
    Message request = ... // create request message
    // setup direct reply-to as reply-to destination
    RMQDestination replyQueue = new RMQDestination(
        "amq.rabbitmq.reply-to", "", "amq.rabbitmq.reply-to", "amq.rabbitmq.reply-to"
    );
    replyQueue.setDeclared(true); // no need to create this destination
    message.setJMSReplyTo(replyQueue);
    MessageConsumer responseConsumer = session.createConsumer(replyQueue);
    BlockingQueue<Message> queue = new ArrayBlockingQueue<>(1);
    responseConsumer.setMessageListener(msg -> queue.add(msg));
    // send request message
    MessageProducer producer = session.createProducer(session.createQueue("request.queue"));
    producer.send(message);
    try {
        // wait response for 5 seconds
        Message response = queue.poll(5, TimeUnit.SECONDS);
        // close the response consumer
        responseConsumer.close();
        return response;
    } catch (InterruptedException e) {
        // deal with exception
    }
});
----

See https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/src/test/spring/com/rabbitmq/integration/tests/RpcSpringJmsIT.java[this test]
for a full example of RPC with Spring JMS, including using a `@JmsListener` bean
for the server part.
