#!/bin/bash
## Run command in all rabbit-jms repositories in situ

# Set up local vars
my_dir=`pwd`
cmd=$1

echo "Run command '$cmd' in rabbit-jms-* Git repositories"

for repoDir in $(find . -type d -name 'rabbit-jms-*')
do
    repo=$repoDir

    echo
    echo '-----------------------------------------------------'
    if [[ -d "$repo/.git" ]] ; then
        echo
        echo "===== entering $repo"
        (cd $repo; $cmd)
    else
        echo
        echo "===== skipping $repo"
    fi
    echo '-----------------------------------------------------'

done
