#!/bin/bash
# Update all RJMS versions in rabbit-jms repos.
# Must be executed in parent directory of repo directories.
# Replies upon bin/update-tag and bin/update-versions.txt files.

set -o errexit
set -o nounset

OLD_VERSION=$1
NEW_VERSION=$2

if [[ -z $NEW_VERSION ]] ; then
    echo 'Not enough parameters: update-rjms-versions oldversion newversion'
    exit 1
fi

if [[ $OLD_VERSION = $NEW_VERSION ]] ; then
    echo 'Versions should be distinct.'
    exit 1
fi

cd bin
echo ''
echo 'Entering ' `pwd`
echo '-------------------------------------------------------------------------------------------------'

source update-versions.txt

cd ..
echo '-------------------------------------------------------------------------------------------------'
echo 'Returning to ' `pwd`
echo ''