name: Test against supported Java versions (2.x)

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        version: [ '8', '11', '17', '21', '22', '23', '24-ea' ]
        include:
          - distribution: 'semeru'
            version: '17'
    name:  Test against Java ${{ matrix.distribution }} ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 2.x.x-stable
      - name: Checkout tls-gen
        uses: actions/checkout@v4
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Start RabbitMQ application
        run: ci/start-broker.sh
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Dtest-broker.A.nodename=rabbit@$(hostname) \
            -Dtest-tls-certs.dir=tls-gen/basic \
            --no-transfer-progress \
            -Dnet.bytebuddy.experimental=true
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
